# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CurvedLabelFixer
                                 A QGIS plugin
 Fix rendering of RTL labels on curved lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-28
        copyright            : (C) 2026 by Dror Bogin
        email                : dror.bogin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CurvedLabelFixer class from file CurvedLabelFixer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .curved_label_fixer import CurvedLabelFixer
    return CurvedLabelFixer(iface)
